#!/usr/bin/env bash
# Configuration in such a manner that HTTP response contains a custom header (on web-01 and web-02)
# Custom name header X-Served-By
# The value of HTTP header should be the hostname of server Nginx is running on
sudo apt-get update
sudo apt-get -y install nginx

# configuration allows request through port 80
sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html

# permissions to allow us easily create files in directory
sudo chmod -R 755 /var/www

#  creation of index page
echo 'Hello World!' |sudo tee  /var/www/html/index.html

# creation a webpage for error 404
echo "Ceci n'est pas une page" |sudo tee /var/www/html/404.html

# code for configuration redirect for a single page(/redirect_me) and add header to display hostname
string_for_replacement="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.blog.ehoneahobed.com permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# code to configure redirect for 404 error page
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# restart web server on updating the settings
sudo service nginx restart
