#!/usr/bin/env bash
# Create script to install&configure Proxy
# Configure HAProxy sending traffic to web-01&web-02 servers
# Requests using algorithm
# Make sure that HAProxy is managed via init script
# Install&Configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# edit the file to config
server_config=\
"
configuration
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enables proxy be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
