#!/usr/bin/env bash
# script displays contents of the file `/etc/passwd`.
# displays the username, user id, & user home directory path.

myfile="/etc/passwd"
while IFS= read -r line
do
    echo "$line" | cut -d":" -f1,3,6
done < "$myfile"
