#!/usr/bin/env bash
# script displaying Best School 10 times and hi after the 9th using while and if loop

k=1

while [ $k -le 10 ]
do
    echo "Best School"
    if [ $k -eq 9 ]
    then
        echo "Hi"
    fi
    ((k++))
done
