#!/usr/bin/env bash
# script display content of current directory in list format
# displays the part of name after the first dash

mylist=$(ls)

for k in $mylist; do
  echo "$k" | cut -d '-' -f2
done
